/*--------------------------------CREACION DE TABLAS------------------------------*/

/*USUARIOS*/
CREATE TABLE USER_DATA(
USER_DNI NUMBER(8) NOT NULL PRIMARY KEY,
USER_NOMBRE VARCHAR(50) NOT NULL,
USER_APELL_PAT VARCHAR(30) NOT NULL,
USER_APELL_MAT VARCHAR(30) NOT NULL,
USER_EMAIL VARCHAR(50),
USER_CEL NUMBER(10),
USER_ESTADO NUMBER NOT NULL,
USER_FECHA_REGISTRO DATE,
USER_FEC_UPDATE DATE
);

CREATE TABLE USER_LOGIN(
USER_DNI NUMBER(8) NOT NULL UNIQUE,
USER_PASS VARCHAR(30) NOT NULL 
);

ALTER TABLE USER_LOGIN ADD FOREIGN KEY (USER_DNI) REFERENCES USER_DATA(USER_DNI);

/*TABLA LOGIN PROVEEDORES*/

CREATE TABLE PROV_LOGIN(
PV_RUC NUMBER(11) NOT NULL UNIQUE,
PV_PASS VARCHAR(30) NOT NULL,
PV_TYPE NUMBER(1) NOT NULL
);

/*TABLA PROVEEDORES*/
CREATE TABLE PROV_DATA(
PV_RUC NUMBER(11) NOT NULL PRIMARY KEY,
PV_RAZON VARCHAR(100) NOT NULL,
PV_DIREC VARCHAR(100) NOT NULL,
PV_CONTAC VARCHAR(30),
PV_CONTAC_NUM NUMBER,
PV_UBI_LAT VARCHAR(40) NOT NULL,
PV_UBI_LON VARCHAR(40) NOT NULL,
PV_EMAIL VARCHAR(30),
PV_HINI VARCHAR(10),
PV_HFIN VARCHAR(10),
PV_ESTADO NUMBER,
PV_FEC_REGISTRO DATE,
PV_FEC_UPDATE DATE
);

ALTER TABLE PROV_LOGIN ADD FOREIGN KEY (PV_RUC) REFERENCES PROV_DATA(PV_RUC);

/*TABLA ARTICULOS*/

CREATE TABLE ARTI_DATA(
ARTI_COD VARCHAR(50) NOT NULL PRIMARY KEY,
ARTI_NOM VARCHAR(100) NOT NULL,
ARTI_DESCRIP VARCHAR(800)NOT NULL,
ARTI_PREC NUMBER NOT NULL,
ARTI_CANT NUMBER NOT NULL,
ID_CAT VARCHAR(10) NOT NULL,
PV_RUC NUMBER(11) NOT NULL,
ARTI_FECHA DATE NOT NULL,
ARTI_FECHA_MOD DATE,
ARTI_ESTADO NUMBER
);

CREATE SEQUENCE GEN_COD_ARTI
INCREMENT BY 1
START WITH 1
NOMINVALUE
NOMAXVALUE;

/*TABLA CATEGORIAS*/
CREATE TABLE CATE_DATA(
ID_CAT VARCHAR(10) NOT NULL PRIMARY KEY,
CAT_NOM VARCHAR(50) NOT NULL
);

/*CREACION TABLA URL IMAGANES ARTICULOS*/

CREATE TABLE IMG_DATA(
ARTI_COD VARCHAR(50) NOT NULL,
RUTA_IMG VARCHAR(50) NOT NULL
);

/*RELACIONES DE TABLAS*/

ALTER TABLE ARTI_DATA ADD FOREIGN KEY (ID_CAT) REFERENCES CATE_DATA(ID_CAT);
ALTER TABLE ARTI_DATA ADD FOREIGN KEY (PV_RUC) REFERENCES PROV_DATA(PV_RUC);
ALTER TABLE IMG_DATA ADD FOREIGN KEY(ARTI_COD) REFERENCES ARTI_DATA(ARTI_COD);

/*CREACION DE TABLAS PARA VENTAS */

CREATE TABLE VENTAS(
VENTA_ID VARCHAR(10) NOT NULL PRIMARY KEY,
USER_DNI NUMBER NOT NULL,
VENTA_T NUMBER NOT NULL,
VENTA_U_LAT NUMBER,
VENTA_U_LONG NUMBER,
VENTA_FECHA DATE NOT NULL,
VENTA_ESTADO NUMBER
);

/*SECUENCIA DE INGRESOS VENTAS*/
CREATE SEQUENCE GEN_COD_VENTA
INCREMENT BY 1
START WITH 1
NOMINVALUE
NOMAXVALUE;

CREATE TABLE DETA_VENTA(
VENTA_ID VARCHAR(10) NOT NULL,
ARTI_COD VARCHAR(50) NOT NULL,
DETA_PREC NUMBER NOT NULL,
DETA_CANT NUMBER NOT NULL,
PV_RUC VARCHAR(11) NOT NULL,
ESTA_ENVIO NUMBER,
ESTA_SELE NUMBER,
PV_RUC_ENVIO NUMBER
);
/*RELACION DE TABLAS VENTAS Y DETALLES */
ALTER TABLE VENTAS ADD FOREIGN KEY (USER_DNI) REFERENCES USER_DATA(USER_DNI);
ALTER TABLE DETA_VENTA ADD FOREIGN KEY (ARTI_COD) REFERENCES ARTI_DATA(ARTI_COD);
ALTER TABLE DETA_VENTA ADD FOREIGN KEY (VENTA_ID) REFERENCES VENTAS(VENTA_ID);


/*---------------------------FIN CREACION DE TABLAS-------------------------*/

/*---------------------------CREACION DEL PROCEDURE---------------------------*/


CREATE OR REPLACE PROCEDURE NEW_USER(
DNI NUMBER,
NOM VARCHAR,
APP VARCHAR,
APM VARCHAR,
EMAIL VARCHAR,
CEL NUMBER,
PASS VARCHAR
)
IS
BEGIN
INSERT INTO USER_DATA VALUES (DNI,NOM,APP,APM,EMAIL,CEL,1,SYSDATE,NULL);
INSERT INTO USER_LOGIN VALUES (DNI,PASS);
END;
/

CREATE OR REPLACE PROCEDURE MOD_USER(
DNI NUMBER,
NOM VARCHAR,
APP VARCHAR,
APM VARCHAR,
EMAIL VARCHAR,
CEL NUMBER,
ESTADO NUMBER
)
IS
BEGIN
UPDATE USER_DATA SET  USER_DNI=DNI, USER_NOMBRE=NOM, USER_APELL_PAT=APP, USER_APELL_MAT=APM, USER_EMAIL=EMAIL,USER_CEL=CEL, USER_ESTADO=ESTADO, USER_FEC_UPDATE=SYSDATE WHERE USER_DNI=DNI;
UPDATE USER_LOGIN SET USER_DNI=DNI WHERE USER_DNI=DNI;
END;
/

CREATE OR REPLACE PROCEDURE DEL_USER(
DNI NUMBER)
IS BEGIN
UPDATE USER_DATA VALUE SET USER_ESTADO=0 WHERE USER_DNI=DNI;
END;
/

CREATE OR REPLACE PROCEDURE NEW_PROV(
RUC NUMBER,
RAZON VARCHAR,
DIREC VARCHAR,
CONTAC VARCHAR,
CONTAC_NUM NUMBER,
UBI_LAT VARCHAR,
UBI_LON VARCHAR,
EMAIL VARCHAR,
PV_HINI VARCHAR,
PV_HFIN VARCHAR,
PV_TYPE NUMBER,
PV_ESTADO NUMBER,
PASS VARCHAR)
IS
BEGIN
INSERT INTO PROV_DATA VALUES (RUC,RAZON,DIREC,CONTAC,CONTAC_NUM,UBI_LAT,UBI_LON,EMAIL,PV_HINI,PV_HFIN,PV_ESTADO,SYSDATE,NULL);
INSERT INTO PROV_LOGIN VALUES (RUC,PASS,PV_TYPE);
END;
/

CREATE OR REPLACE PROCEDURE DEL_PROV(
RUC NUMBER)
IS BEGIN
UPDATE PROV_DATA VALUE SET PV_ESTADO=0 WHERE PV_RUC=RUC;
END;
/

CREATE OR REPLACE PROCEDURE MOD_PROV(
RUC NUMBER,
RAZON VARCHAR,
DIREC VARCHAR,
CONTAC VARCHAR,
CONTAC_NUM NUMBER,
UBI_LAT VARCHAR,
UBI_LON VARCHAR,
EMAIL VARCHAR,
HINI VARCHAR,
HFIN VARCHAR,
ESTADO NUMBER
)
IS
CONT NUMBER;
BEGIN
UPDATE PROV_DATA SET PV_RUC=RUC, PV_RAZON=RAZON, PV_DIREC=DIREC, PV_CONTAC=CONTAC, PV_CONTAC_NUM=CONTAC_NUM, PV_UBI_LAT=UBI_LAT,
PV_UBI_LON=UBI_LON, PV_EMAIL=EMAIL, PV_HINI=HINI, PV_HFIN=HFIN, PV_ESTADO=ESTADO, PV_FEC_UPDATE=SYSDATE WHERE PV_RUC=RUC;
UPDATE PROV_LOGIN SET PV_RUC=RUC WHERE PV_RUC=RUC;
SELECT COUNT(PV_RUC) INTO CONT FROM ARTI_DATA WHERE PV_RUC = RUC;
END;
/










COMMIT;
